{% set name = "nteract-scrapbook" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f78452033c9542c084ede75c9844423ff272cec37511bbf22228c1b29084032

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - ipython
    - jsonschema
    - pandas
    - papermill
    - pyarrow
    - python >=3.5

test:
  requires:
    - coverage
    - ipython
    - mock
    - pip
    - pytest >=4.1
    - pytest-cov >=2.6.1
    - pytest-env >=0.6.2
    - pytest-mock >=1.10
  imports:
    - scrapbook
  commands:
    - python -m pytest --pyargs scrapbook --cov scrapbook -v
    - python -m pip check

about:
  home: https://github.com/nteract/scrapbook
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A library for recording and reading data in notebooks. '
  description: |
    THE scrapbook library records a notebook’s data values and generated visual
    content as "scraps". Recorded scraps can be read at a future time.
  doc_url: https://nteract-scrapbook.readthedocs.io
  doc_source_url: https://github.com/nteract/scrapbook/tree/master/docs

extra:
  recipe-maintainers:
    - bollwyvl
    - mseal
